[package]
name = "gosub_rendering"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_html5 = { path = "../gosub_html5" }
gosub_styling = { path = "../gosub_styling" }
taffy = "0.4.3"
anyhow = "1.0.82"
regex = "1.10.4"
rstar = "0.12.0"



[lints]
workspace = true
