[package]
name = "net"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]

[dependencies]
config = { path = "../config", features = [] }
derive_more = "0.99"
thiserror = "1.0.57"
ureq = "2.9.5"
anyhow = "1.0.79"
log = "0.4.20"
domain-lookup-tree = "0.1"
hickory-resolver = "0.24.0"
simple_logger = "4.2.0"
cookie = { version = "0.18.0", features = ["secure", "private"] }
http = "1.0.0"
url = "2.5.0"