[package]
name = "gosub_css3"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared", features = [] }
lazy_static = "1.4"
log = "0.4.21"
simple_logger = "4.2.0"
anyhow = { version = "1.0.82", features = [] }
colors-transform = "0.2.11"
