[package]
name = "gosub-engine"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"
authors = ["Gosub Community <info@gosub.io>"]
description = "An HTML5 browser engine written in Rust."
license = "MIT"
repository = "https://github.com/gosub-browser/gosub-engine"
readme = "README.md"
keywords = ["html5", "parser", "browser", "Rust", "DOM"]

[workspace]
members = [
    "crates/*"
]

[[example]]
name = "html5-parser"

[[test]]
name = "tokenizer"
path = "tests/tokenizer.rs"

[[test]]
name = "tree_construction"
path = "tests/tree_construction.rs"

[[bench]]
name = "tokenizer"
harness = false

[[bench]]
name = "tree_construction"
harness = false

[[bench]]
name = "tree_iterator"
harness = false

[dependencies]
gosub_shared = { path = "./crates/gosub-shared", features = [] }
gosub_net = { path = "./crates/gosub-net", features = [] }
gosub_config = { path = "./crates/gosub-config", features = [] }
gosub_html5 = { path = "./crates/gosub-html5", features = [] }
gosub_css3 = { path = "./crates/gosub-css3", features = [] }
gosub_js = { path = "./crates/gosub-js", features = [] }
gosub_jsapi = { path = "./crates/gosub-jsapi", features = [] }
gosub_testing = { path = "./crates/gosub-testing", features = [] }
phf = { version = "0.11.2", features = ["macros"] }
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_derive = "1.0"
regex = "1"
lazy_static = "1.4"
#typed-arena = "2.0.2"
thiserror = "1.0.57"
ureq = "2.9.6"
anyhow = "1.0.79"
uuid = { version = "1.7.0", features = ["v4"] }
colored = "2.1.0"
walkdir = "2.3"
nom = "7.1.3"
nom_locate = "4.2.0"
sqlite = "0.33.0"
#wildmatch = "2.2.0"
clap = { version = "4.5.0", features = ["derive"] }
log = "0.4.20"
#domain-lookup-tree = "0.1"
#hickory-resolver = "0.24.0"
simple_logger = "4.2.0"
#libc = "0.2"
#shared_singleton = "0.1.0"
testing_logger = "0.1.1"
cookie = { version = "0.18.0", features = ["secure", "private"] }
#http = "1.0.0"
url = "2.5.0"
v8 = "0.83.2"
#rand = "0.8.5"
#ouroboros = "0.18.3"
chardet = "0.2.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
test-case = "3.3.1"

[features]
# Enables extended debugging information during parsing.
debug_parser = []


[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
#rustflags = ["-C", "target-cpu=native"] # Currently unstable and it can cause problems on older CPUs (don't have newer CPU instructions).

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1

[lib]
crate-type = ["staticlib"]
