[package]
name = "gosub-engine"
version = "0.1.0"
edition = "2021"
rust-version = "1.73"
authors = ["Gosub Community <info@gosub.io>"]
description = "An HTML5 browser engine written in Rust."
license = "MIT"
repository = "https://github.com/gosub-browser/gosub-engine"
readme = "README.md"
keywords = ["html5", "parser", "browser", "Rust", "DOM"]

[workspace]
members = [
  "crates/*"
]

[[example]]
name = "html5-parser"

[[test]]
name = "tokenizer"
path = "tests/tokenizer.rs"

[[test]]
name = "tree_construction"
path = "tests/tree_construction.rs"

[[bench]]
name = "tokenizer"
harness = false

[[bench]]
name = "tree_construction"
harness = false

[[bench]]
name = "tree_iterator"
harness = false

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
regex = "1"
lazy_static = "1.4"
typed-arena = "2.0.2"
thiserror = "1.0.50"
ureq = "2.8.0"
anyhow = "1.0.75"
uuid = { version = "1.6.0", features = ["v4"] }
colored = "2.0.4"
walkdir = "2.3"
nom = "7.1.3"
nom_locate = "4.2.0"
sqlite = "0.32.0"
wildmatch = "2.1.1"
clap = { version = "4.4.8", features = ["derive"] }
cli-table = "0.4.7"
textwrap = "0.16.0"
log = "0.4.20"
domain-lookup-tree = "0.1"
hickory-resolver = "0.24.0"
simple_logger = "4.2.0"
libc = "0.2"
shared_singleton = "0.1.0"
testing_logger = "0.1.1"
cookie = { version = "0.18.0", features = ["secure", "private"] }
http = "1.0.0"
url = "2.5.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
test-case = "3.3.1"

[features]
# Enables extended debugging information during parsing.
debug_parser = []
