[package]
name = "gosub-engine"
version = "0.1.0"
edition = "2021"
authors = ["Joshua Thijssen <jaytaph@deadcode.nl>"]

description = "html5 browser engine"
license = "MIT"
repository = "https://github.com/jaytaph/gosub-browser"
readme = "README.md"
keywords = ["html5", "parser"]

[[test]]
name = "tokenizer"
path = "tests/tokenizer.rs"

[[bench]]
name = "tokenizer"
harness = false

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
derive_more = "0.99"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1"
lazy_static = "1.4"
typed-arena = "2.0.2"
thiserror = "1.0.49"
ureq = "2.8.0"
anyhow = "1.0.75"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
test-case = "3.2.1"
