[package]
name = "gosub_styling"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_css3 = { path = "../gosub_css3" }
gosub_html5 = { path = "../gosub_html5" }
gosub_render_backend = { path = "../gosub_render_backend" }
gosub_typeface = { path = "../gosub_typeface" }
lazy_static = "1.4"
anyhow = "1.0.86"
regex = "1.10.4"
colors-transform = "0.2.11"
vello = "0.2.0"

#[target.'cfg(target_arch = "wasm32")'.dependencies]
#web-sys = { version = "0.3.69", features = ["fontface"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rust-fontconfig = "0.1.7"