[package]
name = "gosub_renderer"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gosub_rendering = { path = "../gosub_render_utils" }
gosub_html5 = { path = "../gosub_html5" }
gosub_shared = { path = "../gosub_shared" }
gosub_styling = { path = "../gosub_styling" }
gosub_net = { path = "../gosub_net" }
taffy = "0.4.1"
vello = "0.1.0"
winit = "0.30.0"
anyhow = "1.0.86"
wgpu = "0.19.3"
futures = "0.3.30"
slotmap = "1.0.7"
smallvec = "1.13.2"
image = "0.25.1"
url = "2.5.0"



[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.42"
web-sys = "0.3.55"